### ISSUE TITLE
AttributeError: 'CacheManager' object has no attribute 'location'

### ISSUE THREAD

**Issue by Boeing737ng** [lezakkaz/DrawSomething#2]
After using 'git pull' command, I installed all things in requirements and when i try running routes.py, the error occurred with this message. any idea??

<img width="962" alt="2018-08-12 11 15 23" src="https://user-images.githubusercontent.com/24473927/44002988-7c522156-9e86-11e8-955a-633822fa7610.png">

**Comment by HyeokjuJang** [comment]
I'm sorry for the late answer.
There was something changed in magenta module.
So I make magenta folder that worked before.
Pull again please

**Comment by Boeing737ng** [comment]
I did pull again and tried but it still shows same Attribute error.. does it work well in your environment?

**Comment by HyeokjuJang** [comment]
* Serving Flask app "routes" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Aug/2018 13:36:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2018 13:36:15] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2018 13:36:15] "GET /static/js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2018 13:36:15] "GET /static/js/paper-core.js HTTP/1.1" 404 -
INFO:tensorflow:Model using gpu.
INFO:tensorflow:Input dropout mode = False.
INFO:tensorflow:Output dropout mode = False.
INFO:tensorflow:Recurrent dropout mode = False.
WARNING:tensorflow:From /Users/hyeokjujang/env/draw_tmp/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From /Users/hyeokjujang/env/draw_tmp/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
WARNING:tensorflow:From /Users/hyeokjujang/Desktop/git/DrawSomething/magenta/models/sketch_rnn/model.py:287: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /Users/hyeokjujang/Desktop/git/DrawSomething/magenta/models/sketch_rnn/model.py:297: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

INFO:tensorflow:Model using gpu.
INFO:tensorflow:Input dropout mode = 0.
INFO:tensorflow:Output dropout mode = 0.
INFO:tensorflow:Recurrent dropout mode = 0.
INFO:tensorflow:Model using gpu.
INFO:tensorflow:Input dropout mode = 0.
INFO:tensorflow:Output dropout mode = 0.
INFO:tensorflow:Recurrent dropout mode = 0.
2018-08-14 13:36:22.307075: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Loading model ./static/model_autoencoder/models/catbus/vector.
INFO:tensorflow:Restoring parameters from ./static/model_autoencoder/models/catbus/vector
<IPython.core.display.SVG object>
127.0.0.1 - - [14/Aug/2018 13:36:23] "GET /auto?model=catbus HTTP/1.1" 200 -



Yeah it works. I checked it again now.  
I don't know your previous codes. Have you tried clone it? not pull.

**Comment by HyeokjuJang** [comment]
I checked it by making new environment and installing requirements again.
Of course clone the git.

**Comment by Boeing737ng** [comment]
Yeah, I don't know why but it works after I clone the project again. Anyway it's perfect now! Thanks!
